### ISSUE TITLE
:Typescript commands are not created after install

### ISSUE THREAD

**Issue by jugarpeupv** [jose-elias-alvarez/typescript.nvim#1]
Hello,

After installation and configuration i dont see the commands created, is it normal?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/69123204/163710171-77e31493-6ef1-478d-b9ef-8a764e301b90.png">

I see this problems in the source code and tried installed that npm package but still givin the error
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/69123204/163710246-156d2397-fbb9-4d18-ab06-0827143c43e3.png">

Is it because this plugin is still in development? I am just searching a way to add import all functionality to nvim

**Comment by mmirus** [comment]
Took me a bit to figure this out, but I think that you need to remove your existing tsserver LSP config setup and instead call `require("typescript").setup()`.

For example, I had something like this:

```lua
local servers = { ..., "tsserver", ... }
for _, lsp in pairs(servers) do
  local options = {
      on_attach = on_attach,
      flags = {
        debounce_text_changes = 150,
      },
      capabilities = capabilities,
  }
  lspconfig[lsp].setup(options)
end
```

To initialize a bunch of language servers.

But this plugin seems to take over setting up tsserver from lsp-config, so that needed to be changed:

```lua
local servers = { ... }
-- 👆 note that tsserver is not here anymore
for _, lsp in pairs(servers) do
  local options = {
      on_attach = on_attach,
      flags = {
        debounce_text_changes = 150,
      },
      capabilities = capabilities,
  }
  lspconfig[lsp].setup(options)
end

-- Set up tsserver separately using typescript.nvim:
require("typescript").setup({
  server = {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    },
    capabilities = capabilities,
  }
})
```

**Comment by jugarpeupv** [comment]
Many thanks @mmirus it makes sense, ill have to refactor a bit my actual code

**Comment by mmirus** [comment]
No need to apologize! Thanks for being the one to take on this work that we all benefit from.

**Comment by jose-elias-alvarez** [comment]
I added a mention of a couple of potential pitfalls in a26f013872444bc8c43298c97f41a07044086c71. Let me know if you run into any other problems.

**Comment by LoydAndrew** [comment]
How to setup it with lsp-installer.lua? 
This approach from their [wiki](https://github.com/williamboman/nvim-lsp-installer/wiki/Rust) doesn't work
```lua
    if server.name == "tsserver" then
        require("typescript").setup({
            server = vim.tbl_deep_extend("force", server:get_default_options(), opts)
        })
        server:attach_buffers()
    end

```

**Comment by lucasmarinb** [comment]
> How to setup it with lsp-installer.lua? This approach from their [wiki](https://github.com/williamboman/nvim-lsp-installer/wiki/Rust) doesn't work
> 
> ```lua
>     if server.name == "tsserver" then
>         require("typescript").setup({
>             server = vim.tbl_deep_extend("force", server:get_default_options(), opts)
>         })
>         server:attach_buffers()
>     end
> ```

Hi, it might be a bit late, but i've just setup the library alongside `lsp-installer.lua`. Actually, I didn't have to do much since (from what i understand) lsp-installer's only job is to make the language server available, so my `tsserver.lua` config looks like this:

```lua
local function setup(on_attach, capabilities)
	require("typescript").setup({
		server = {
			on_attach = attach,
			capabilities = capabilities,
		},
	})
end

return {
	setup = setup,
}
```
