### ISSUE TITLE
How to rename both file and folder?

### ISSUE THREAD

**Issue by jrafaaael** [jose-elias-alvarez/typescript.nvim#10]
I have a folder structure like:
```
project-name/
├─ components/
│  ├─ Navbar/
│  │  ├─ Navbar.tsx
```
when I rename the Navbar file all works fine but if I try to rename both folder and file to get some like that:
```
project-name/
├─ components/
│  ├─ Navbar2/
│  │  ├─ Navbar2.tsx
```
I get an error... How I can handle this?

**Comment by jose-elias-alvarez** [comment]
This would need to be implemented upstream in typescript-language-server. I had written a very tortured workaround for this that involved scanning a directory's files, but as it goes against the philosophy of this plugin, I don't plan on implementing it here.

**Comment by jrafaaael** [comment]
VSCode can track the rename of the files and the folders separately: you cannot rename the folder and the file in one action. Maybe a second command `:TypescriptRenameFolder` could be one solution

**Comment by jose-elias-alvarez** [comment]
Unlike Neovim, VS Code doesn't have to use `typescript-language-server` as an intermediary between the editor and `tsserver`, so its behavior is quite different (it also contains a large number of off-spec features and optimizations specifically for TypeScript which we wouldn't be able to replicate either way). This isn't a matter of having a separate command - until the language server supports it, I don't plan on adding support here.

**Comment by jrafaaael** [comment]
Thank you!
