### ISSUE TITLE
How to disable formatting capabilities of this plugin?

### ISSUE THREAD

**Issue by jrafaaael** [jose-elias-alvarez/typescript.nvim#11]

**Comment by jose-elias-alvarez** [comment]
This plugin doesn't have any formatting capabilities - those are provided by `tsserver`. 

The recommended approach on 0.8 is to use the new `vim.lsp.buf.format` API, which has a `filter` function that you can use to never request formatting from `tsserver`. On 0.7, you can follow the recommendations in [this article](https://github.com/neovim/nvim-lspconfig/wiki/Multiple-language-servers-FAQ#i-see-multiple-formatting-options-and-i-want-a-single-server-to-format-how-do-i-do-this).
