### ISSUE TITLE
Is there a possibility of omnifunc autocompletion?

### ISSUE THREAD

**Issue by microo8** [jose-elias-alvarez/typescript.nvim#16]
I don't know how to set up omnifunc.

So that if I write `this.` then press `C-xC-o` it just writes: *E764: Option 'omnifunc' is not set*

**Comment by jose-elias-alvarez** [comment]
This isn't specific to the plugin, but the first entry of `:help lsp-config` describes how to set this up. The recommended place to do this would be in your `on_attach` callback.

**Comment by microo8** [comment]
thanks, it's simple as `vim.bo.omnifunc = 'v:lua.vim.lsp.omnifunc'`
