### ISSUE TITLE
Add handler for `_typescript.rename`

### ISSUE THREAD

**Issue by ajitid** [jose-elias-alvarez/typescript.nvim#17]
**Type**: Feature request

We need to first understand why we need to add this.

To reproduce:
1. Write the following code in a TypeScript file

```ts
setInterval(() => {
  console.log(s);
}, 1000);
```

2. Now visually select the anonymous function and invoke a range code action. It would be `:'<,'>lua vim.lsp.buf.range_code_action()`
3. This would give you a code action "Extract to function in module scope". Invoke it.
4. You would see the code has changed but would also notice an error echo `tsserver: -32601: MethodNotFound`
5. Upon inspecting LSP log you would see `server_request: no handler found for _typescript.rename`

In VS Code, the editor asks you provide a new name for the function after the code action is performed. In neovim+typescript.nvim,  it could only perform the code action as the aforementioned handler is missing.

## The solution?

I have written a [handler in Lua](https://github.com/ajitid/dotfiles/blob/30dfcb69a0053fd9e266f748cd02d83f3e85322f/nvim/.config/nvim/lua/mine/lsp/lsp-and-completion.lua#L248-L256). This makes nvim behave same as VS Code. Do note that I assume the position given by tsserver is for UTF-16 text. I do not rely on off-spec `client.offset_encoding` and would rather wait until tsserver starts supporting [positionEncodings](https://github.com/microsoft/language-server-protocol/commit/f9c85d535bbbf918d2433c034f20f99ddadf0ba1) (if it still hasn't yet).

**Edit**: You can find the [updated handler here](https://github.com/ajitid/dotfiles/blob/d60b6ee34f7f2640bfe149503b255290ddfb6996/nvim/.config/nvim/lua/mine/lsp/lsp-and-completion.lua#L248-L256) which uses Lua API finstead for setting the cursor position.

**Comment by jose-elias-alvarez** [comment]
This is great! I think this would be a sensible inclusion and a straight-up improvement over the current behavior. I'm not in love with the need to move the cursor, but it does replicate VS Code's behavior perfectly so I think it's fine.

I'm definitely open to reviewing a PR if you want to go ahead and put one together. At a glance, the only thing I'd change is preferring API methods over Vimscript functions (e.g. `nvim_win_set_cursor` over `vim.fn.cursor`).

**Comment by ajitid** [comment]
I'm unsure what the benefit is of writing `nvim_win_set_cursor` over the Vimscript fn. (Honestly I never liked how the names are in Lua counterpart.) That being said, I've changed it in my dotfiles. 

> I'm definitely open to reviewing a PR if you want to go ahead and put one together. 

Jose, would it possible for you to work on this? I don't use this plugin, but thought many other users do and hence opened a ticket for it.

**Comment by jose-elias-alvarez** [comment]
> Jose, would it possible for you to work on this? 

Sure, happy to take this over when I have time. Thanks for raising the issue!

**Comment by jose-elias-alvarez** [comment]
Added in e4b780d6b686585cb345e16d444fd3d303da91bb. Thanks again for the idea and for providing a sample implementation!

**Comment by mmirus** [comment]
Thank you both! It's awesome seeing the neovim support for these actions get more full featured.
