### ISSUE TITLE
Duplicate logs with eslint lsp server.

### ISSUE THREAD

**Issue by mattiasbonte** [jose-elias-alvarez/typescript.nvim#19]
Good day!

Would it be possible to adjust the `log-level` as well through this plugin's config?
I'm using eslint and tsserver together and I'm seeing (kinda) duplicate error logs, which I assume comes from my `.eslintrc.js` in my project and the one being used by the `tsserver`? I have not really plunged into the depths of linters and so I might be wrong.

![image](https://user-images.githubusercontent.com/65280774/180650976-aaa7ed82-09d8-4ef3-8aef-adfea662cead.png)

I'm interested to hear what your approach would be to this? I was thinking of reducing the log-level op the tsserver.

**Comment by jacksonludwig** [comment]
I believe this was a feature supported in https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils, where you could do something like `filter_out_diagnostics_by_severity` or `filter_out_diagnostics_by_code`.

However, I do not know if that follows this plugin's goal of being more minimal and only supporting existing `tsserver` features.

I would be interested to know of any other way to handle this issue besides changing my eslint/tsserver config in my project.

**Comment by jose-elias-alvarez** [comment]
This is pretty straightforward to achieve by overriding the handler:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = function(_, result, ctx, ...)
    local client = lsp.get_client_by_id(ctx.client_id)

    if client and client.name == "tsserver" then
        result.diagnostics = vim.tbl_filter(function(diagnostic)
            -- use whatever condition you want to filter diagnostics
            return not diagnostic.message:find("is declared but its value is never read")
        end, result.diagnostics)
    end

    return lsp.diagnostic.on_publish_diagnostics(nil, result, ctx, ...)
end
```

> However, I do not know if that follows this plugin's goal of being more minimal and only supporting existing tsserver features.

This is definitely part of it, but more than anything, since Neovim makes it easy to do this for any language server, I don't think it makes sense to include it here.

**Comment by mattiasbonte** [comment]
Thank you for the quick and detailed answer! I see I wasn't completely clear in my question.. I wasn't really looking for a way to disable specific log messages, but that will definitely come in handy at some point.

I'm actually trying to find out if it's possible to decrease the [overall log level](https://github.com/typescript-language-server/typescript-language-server#cli-options=) to for example 1. By default it's 3 if I'm not mistaken.

Would it be possible to somehow pass this into the `setup->server->on_attach` function for example? Or is that also something I should change inside the handler?

**Comment by jose-elias-alvarez** [comment]
I'm a little confused by your example, since the messages shown in your screenshots are not logs but diagnostics. If you want to modify / suppress those, you can use the code I provided as an example. 

If you're referring to file logs, you can check out `:help ls-log` in Neovim to see the available methods. You can also modify the arguments used to spawn `typescript-language-server` by [overriding the `cmd` field passed to nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver). If you're using this plugin, that would look like this:

```lua
require("typescript").setup({
    server = {
        cmd = { "typescript-language-server", "--stdio", "--log-level", "1" },
    },
})
```

For your second question: there's no interaction whatsoever between `tsserver` and ESLint, so `tsconfig.json` is what you'd want to target here.

**Comment by mattiasbonte** [comment]
Your confusion is my mistake.. I did mistake log-level for diagnostic-level apparently. Thank your patience and help!
