### ISSUE TITLE
Setup with lsp-installer

### ISSUE THREAD

**Issue by LoydAndrew** [jose-elias-alvarez/typescript.nvim#2]
Hello. I've read the first issue about setup, but it doesn't help cause lsp-installer have a special method of server's setup. 

This approach from their [wiki](https://github.com/williamboman/nvim-lsp-installer/wiki/Rust) doesn't work
```lua
    if server.name == "tsserver" then
        require("typescript").setup({
            server = vim.tbl_deep_extend("force", server:get_default_options(), opts)
        })
        server:attach_buffers()
    end
``

**Comment by jose-elias-alvarez** [comment]
Good question, not sure why the approach recommended for rust-tools doesn't work here. I don't personally use lsp-installer, but if you can investigate and determine if we're doing wrong on our end I'm happy to make changes to support it.

**Comment by LoydAndrew** [comment]
Okay. lsp-installer recently changed it's setup method and it's now using lspconfig.setup(). So instructions from the wiki is completely applicable to lsp-installer too.
