### ISSUE TITLE
Commands are not available in command mode

### ISSUE THREAD

**Issue by lucasmarinb** [jose-elias-alvarez/typescript.nvim#20]
Hi, I just installed this library but i noticed that the commands described in the `Commands` section do not appear while in command mode, so for instance typing `:Ty` and then `<Tab>` don't generate any autocomplete options. Is this the intended behavior?

**Comment by jose-elias-alvarez** [comment]
Assuming you're using the default configuration, commands are buffer-local, so you'll only see them in buffers that have attached to `tsserver` (which also depends on your settings but should default to JavaScript + TypeScript and friends). Is that not the case for you?

**Comment by lucasmarinb** [comment]
Oh, classic RTFM moment :sweat_smile:. I was actually looking for them while editing my `lua` files.

Thank you for yout reply!
