### ISSUE TITLE
Not clear how to make it work with tsserver lspconfig

### ISSUE THREAD

**Issue by strdr4605** [jose-elias-alvarez/typescript.nvim#21]
I have this config for lsp:
```lua
local status_ok, mason_lspconfig = pcall(require, "mason-lspconfig")
if not status_ok then
  return
end

local mason = require("mason")
local lspconfig = require("lspconfig")

local servers = { "jsonls", "sumneko_lua", "tsserver", "cssls" }

mason.setup()
mason_lspconfig.setup({
  ensure_installed = servers,
})

for _, server in pairs(servers) do
  local opts = {
    on_attach = require("user.lsp.handlers").on_attach,
    capabilities = require("user.lsp.handlers").capabilities,
  }
  local has_custom_opts, server_custom_opts = pcall(require, "user.lsp.settings." .. server)
  if has_custom_opts then
    opts = vim.tbl_deep_extend("force", opts, server_custom_opts)
  end
  lspconfig[server].setup(opts)
end
```
https://github.com/strdr4605/.dotfiles/blob/master/nvim/lua/user/lsp/configs.lua

and I call `require("typescript").setup()` here: https://github.com/strdr4605/.dotfiles/blob/master/nvim/lua/user/lsp/null-ls.lua

As I understand from the note in README, I should not call `lspconfig[server].setup(opts)` with `tsserver`.
I tried:

```diff
```lua
local status_ok, mason_lspconfig = pcall(require, "mason-lspconfig")
if not status_ok then
  return
end

local mason = require("mason")
local lspconfig = require("lspconfig")

- local servers = { "jsonls", "sumneko_lua", "tsserver", "cssls" }
+ local servers = { "jsonls", "sumneko_lua", "cssls" }


mason.setup()
mason_lspconfig.setup({
  ensure_installed = servers,
})

for _, server in pairs(servers) do
  local opts = {
    on_attach = require("user.lsp.handlers").on_attach,
    capabilities = require("user.lsp.handlers").capabilities,
  }
  local has_custom_opts, server_custom_opts = pcall(require, "user.lsp.settings." .. server)
  if has_custom_opts then
    opts = vim.tbl_deep_extend("force", opts, server_custom_opts)
  end
  lspconfig[server].setup(opts)
end

+ require("typescript").setup()
```

But lsp for TS is not working anymore. What am I doing wrong?

**Comment by jose-elias-alvarez** [comment]
As the README says, you need to pass any options you would normally pass to nvim-lspconfig under the `server` key. I don't use mason.nvim and haven't tested this, but it should get you on the right track:

```lua
local status_ok, mason_lspconfig = pcall(require, "mason-lspconfig")
if not status_ok then
    return
end

local mason = require("mason")
local lspconfig = require("lspconfig")

local servers = { "jsonls", "sumneko_lua", "tsserver", "cssls" }

mason.setup()
mason_lspconfig.setup({
    ensure_installed = servers,
})

for _, server in pairs(servers) do
    local opts = {
        on_attach = require("user.lsp.handlers").on_attach,
        capabilities = require("user.lsp.handlers").capabilities,
    }
    local has_custom_opts, server_custom_opts = pcall(require, "user.lsp.settings." .. server)
    if has_custom_opts then
        opts = vim.tbl_deep_extend("force", opts, server_custom_opts)
    end
    -- add a special case for tsserver, since we want to go through typescript.nvim here
    if server == "tsserver" then
        require("typescript").setup({ server = opts })
    else
        lspconfig[server].setup(opts)
    end
end
```

**Comment by strdr4605** [comment]
Looks like it's working for now! Thanks

**Comment by maxcountryman** [comment]
Should Mason manage `tsserver`? I'm unclear on if this plugin will manage the LSP directly; if so, then I think Mason should likely not manage it also.

**Comment by maxcountryman** [comment]
Does it manage the `tsserver` installation itself?

**Comment by jose-elias-alvarez** [comment]
No. It does what nvim-lspconfig does + added commands and defaults, nothing else.

**Comment by bnwa** [comment]
> Not to necro bump, but I was able to get this working in a way that is much more in line with the Maso-lspconfig repo's design and wanted to share it for the next person who finds this issue:
> 
> ```
>   require("mason-lspconfig").setup_handlers {
>     function (server_name) -- default handler (optional)
>         require("lspconfig")[server_name].setup {}
>     end,
> 
>     ["tsserver"] = function ()
>       ts_config.setup({
>         server = { ... }
>       })
>     end
>   }
> ```
> 
> Just specify the tsserver in the setup_handler method and then instead of using lspconfig, use the typescript.nvim plugin to do the setup.

Is there any way to expose the code actions in such a way that they would appear in e.g. [code-action-menu](https://github.com/weilbith/nvim-code-action-menu)?
