### ISSUE TITLE
Is it possible to set user preference options?

### ISSUE THREAD

**Issue by mattiasbonte** [jose-elias-alvarez/typescript.nvim#23]
Hello,

I'm trying to set [this user preference option](https://github.com/Microsoft/TypeScript/blob/main/lib/protocol.d.ts#L2645) to "non-relative", but so far I have had no success.
- `importModuleSpecifierPreference = "non-relative"`

Is it possible to set this inside the config of this plugin? Or is this not within it's scope?

Cheers!

My config
```lua
typescript.setup({
	server = { -- pass options to lspconfig's setup method
		on_attach = function(client, bufnr)
			if client.name == "tsserver" then
				client.server_capabilities.importModuleSpecifierPreference = "project-relative"	
		end,
	},
})
```

**Comment by jose-elias-alvarez** [comment]
Yep, this should be possible, but this needs to be set in the server's initialization options, not as a capability:

```lua
require("typescript").setup({
    server = {
        init_options = {
            importModuleSpecifierPreference = "project-relative",
        },
    },
})
```

See the [typescript-language-server documentation](https://github.com/typescript-language-server/typescript-language-server#initializationoptions) for details.

**Comment by mattiasbonte** [comment]
Thanks Jose, that made my day :).

Couldn't get it to work, but looking closely at the link you've send me this did the trick.

```json
server = {
	init_options = {
		preferences = {
			importModuleSpecifierPreference = "non-relative", 
		},
	},
}
```

**Comment by jose-elias-alvarez** [comment]
Glad you figured it out! I updated my post in case anybody else is curious about this in the future.
