### ISSUE TITLE
Organize and delete unused

### ISSUE THREAD

**Issue by marcioflaviof** [jose-elias-alvarez/typescript.nvim#24]
It's possible to map organize imports and delete unused imports into just one keymap?

**Comment by jose-elias-alvarez** [comment]
See #5, which has information about chaining commands. The basic answer is that there's not really a clean way to do this because of how the language server works, but it's possible to work around that by adding a delay.

**Comment by marcioflaviof** [comment]
Thanks for the fast answer

**Comment by scmx** [comment]
Here's a command that organizes and deletes unused imports
```lua
vim.lsp.buf.execute_command({command = "_typescript.organizeImports", arguments = {vim.fn.expand("%:p")}})
```

Or as a function and tsserver command
```lua
local function organize_imports()
  local params = {
    command = "_typescript.organizeImports",
    arguments = {vim.api.nvim_buf_get_name(0)},
    title = ""
  }
  vim.lsp.buf.execute_command(params)
end

lspconfig.tsserver.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  commands = {
    OrganizeImports = {
      organize_imports,
      description = "Organize Imports"
    }
  }
}
```

All from this reddit thread https://www.reddit.com/r/neovim/comments/lwz8l7/how_to_use_tsservers_organize_imports_with_nvim/
