### ISSUE TITLE
It's possible to organize imports in 'blocks'?

### ISSUE THREAD

**Issue by marcioflaviof** [jose-elias-alvarez/typescript.nvim#25]
You know if it's possible to organize the code imports in 'blocks' instead of organize everything together? For example:
```js
  import b from '@b'
  import c from '@c'
  import a from '@a'
  
  import as from 'bs'
  import as from 'cs'
  import as from 'as'
  
// after organize

  import a from '@a'
  import b from '@b'
  import c from '@c'
  
  import as from 'as'
  import as from 'bs'
  import as from 'cs'

```

**Comment by marcioflaviof** [comment]
Thanks for the plugin, it's helping a lot  :smile:

**Comment by jose-elias-alvarez** [comment]
Thanks for the kind words! Unfortunately there is no option to do this with `typescript-language-server`, but there are ESLint plugins that handle this nicely. I've had success with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md).

**Comment by andresatierf** [comment]
> Thanks for the kind words! Unfortunately there is no option to do this with `typescript-language-server`, but there are ESLint plugins that handle this nicely. I've had success with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md).

@jose-elias-alvarez is it possible to make `:TypescriptOrganizeImports` use the eslint configuration?
I tried to add the desired configuration to `.eslintrc.json` and it works with `:EslintFixAll` but not with `:TypescriptOrganizeImports`

**Comment by jose-elias-alvarez** [comment]
`:TypescriptOrganizeImports` invokes `typescript-language-server`, which has no awareness of ESLint. `:EslintFixAll` is the right command to use in this case (I don't think you'd want to run both, since you'd have conflicts and other weird behavior).
