### ISSUE TITLE
Investigate replacing nvim-lspconfig dependency with `vim.lsp.start`

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/typescript.nvim#29]
I originally wanted this plugin to be independent but quickly found that replacing nvim-lspconfig meant reinventing the wheel (which was particularly painful when going through TypeScript). `vim.lsp.start` makes this a lot easier, though I still think there's a good amount of effort required to reach parity with nvim-lspconfig.

I've been able to set up a minimal example pretty easily, but I think it's the edge cases that make this difficult. I want to investigate how feasible this is and check out other plugins using `vim.lsp.start` to see how they're handling it, because I do think removing the dependency is the right path forwards.

**Comment by CRAG666** [comment]
https://github.com/CRAG666/dotfiles/tree/master/config/nvim
Maybe my dotfiles help with this task, check the ftplugins

**Comment by jose-elias-alvarez** [comment]
Closing as not planned for the reasons described in the linked PR.
