### ISSUE TITLE
Use `on_attach` function instead `setup`

### ISSUE THREAD

**Issue by aspeddro** [jose-elias-alvarez/typescript.nvim#35]
Servers follow a specification so it is common for users to have an `on_attach` function for all servers. In general they have a module to configure each server.

So an easier way for me to have a function like this:

```lua
local on_attach = function(client, bufnr)
  if client.name == 'tsserver' then
    require('typescript').on_attach(client, bufnr, {
      disable_commands = false,
    })
  end
end
```

Let the user do the setup following the `nvim-lspconfig` plugin so he can configure it however he wants. 

Thanks for this plugin!

**Comment by jose-elias-alvarez** [comment]
You can pass `on_attach` under the `server` key - [the README](https://github.com/jose-elias-alvarez/typescript.nvim#setup) has an example of this.
