### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by cyberia-ng** [jose-elias-alvarez/typescript.nvim#4]
I would like to port the code from rename-file.ts to a Lua snippet to include in my config, but without installing the whole plugin.

I can't do this at the moment because this project has no licence and therefore automatically falls under "all rights reserved".

(In fact, even users of this plugin are doing so in contravention of copyright law, since there is no automatic right of usage.)

**Comment by jose-elias-alvarez** [comment]
Added in 1add655c7ecf1f61df9a40b43973b0394d9ae9c4.
