### ISSUE TITLE
Autocompletion for .svg and .png files doesnt work

### ISSUE THREAD

**Issue by timsofteng** [jose-elias-alvarez/typescript.nvim#40]
Hello.
Autocompletion for .svg and .png files doesn't work.

E.g
`import { ReactComponent as Logo } from "../assets/<spot>"`
If I trigger `cmp` autocompletion in <spot> with `lsp` source I cannot see any images, only inner dirs if such exist.

**Comment by jose-elias-alvarez** [comment]
Have you tried passing cmp's `capabilities` table to the server? See my comment in #34.

**Comment by jose-elias-alvarez** [comment]
I believe the fix described in #34 should fix this, but feel free to open another issue if not.
