### ISSUE TITLE
Odd startup error

### ISSUE THREAD

**Issue by LandonSchropp** [jose-elias-alvarez/typescript.nvim#41]
I'm using LunarVim, and I've set up typescript.nvim in Packer by following the instructions in the readme.

``` lua
  {
    "jose-elias-alvarez/typescript.nvim",
    config = function()
      require("typescript").setup()
    end,
  },
```

When I start my editor, I'm getting the following error.

```
packer.nvim: Error running config for typescript.nvim: vim/shared.lua:0: after the second argument: expected table, got nil
```

I'm using the latest version of Neovim (0.8.0), and the latest version of typescript.nvim.

Any idea what could be causing this?

**Comment by jose-elias-alvarez** [comment]
Have you tried passing an empty table into `setup()`?

**Comment by LandonSchropp** [comment]
Yep! I tried that as well, but I'm running into the same issue.

**Comment by VongoSanDi** [comment]
> Have you tried passing an empty table into `setup()`?

Had same issue, passed an empty table, resolved it.
Thanks.

**Comment by vricop** [comment]
> 

 This removes the pre-defined LSP stuff that come with LunarVim. ¿Is there another way to enable this plugin?

**Comment by vricop** [comment]
> I'm using LunarVim, and I've set up typescript.nvim in Packer by following the instructions in the readme.
> 
> ```lua
>   {
>     "jose-elias-alvarez/typescript.nvim",
>     config = function()
>       require("typescript").setup()
>     end,
>   },
> ```
> 
> When I start my editor, I'm getting the following error.
> 
> ```
> packer.nvim: Error running config for typescript.nvim: vim/shared.lua:0: after the second argument: expected table, got nil
> ```
> 
> I'm using the latest version of Neovim (0.8.0), and the latest version of typescript.nvim.
> 
> Any idea what could be causing this?


This removes the pre-defined LSP stuff that come with LunarVim. ¿Is there another way to enable this plugin?

**Comment by LandonSchropp** [comment]
@vricop I ended up switching over to LazyVim. [Here's](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/typescript.lua) what they do.

**Comment by vricop** [comment]
> @vricop I ended up switching over to LazyVim. [Here's](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/typescript.lua) what they do.

I did something similar, I built my own IDE using the lazy package manager. Now everything just works the way I wanted. You can take a look at my dotfiles. I learned a lot in the process.
