### ISSUE TITLE
Add ability to append null-ls actions to the end

### ISSUE THREAD

**Issue by kristijanhusak** [jose-elias-alvarez/typescript.nvim#45]
Hi,

recently you added support to append code actions to null-ls. They are working fine, but I would like to have them appended at the end instead of showing them first. Currently, if I have something that I want to import, it is in 5th place or more in the code actions list, where usually it's in the first place. Is this even possible with null-ls?

**Comment by jose-elias-alvarez** [comment]
This question has come up before with null-ls, and I'm not sure if there's a good way to do this. If there is, I think it would have to be configured in the UI you are using to select code actions. For example, if you're using `vim.lsp.buf.code_action()`, you could theoretically wrap `vim.ui.select` to sort the [list of actions](https://github.com/neovim/neovim/blob/d25889ab7607918a152bab5ce4d14e54575ec11b/runtime/lua/vim/lsp/buf.lua#L702) before displaying them.

**Comment by jose-elias-alvarez** [comment]
Closing this as I don't believe it's within our control, unfortunately (this has been a super common request from the beginning).
