### ISSUE TITLE
Add customization to import sorter

### ISSUE THREAD

**Issue by sarmong** [jose-elias-alvarez/typescript.nvim#46]
It is more or less a good practice to have `import React from 'react'` at the top of all other imports, but this plugin sometimes does it differently.

This can be added as a customization option that would allow users defining their own order like [eslint import order](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md).

Or some most common framework / library imports can be set inside the plugin as the first priority.

**Comment by jose-elias-alvarez** [comment]
I looked into this a while back, but the server doesn't accept any parameters for the request that would allow us to do this, so I don't think it's possible without somethingl ike the ESLint plugin.

**Comment by sarmong** [comment]
Maybe then typescript.nvim could somehow detect if eslint is connect (say via null-ls) and use it. And if not - use tsserver. Do you think it's feasable?

**Comment by jose-elias-alvarez** [comment]
Hmm, it sounds handy as a user customization, but I think it's out-of-scope for this plugin (especially because it's hard to know whether ESLint is capable of sorting imports, since there are multiple plugins). This is how I would do it using the ESLint language server:

```lua
vim.api.nvim_create_user_command("SortImports", function()
    local clients = vim.lsp.get_active_clients({ bufnr = vim.api.nvim_get_current_buf() })
    local eslint_client = vim.tbl_filter(function(client)
        return client.name == "eslint"
    end, clients)[1]

    if eslint_client then
        vim.lsp.buf.format({ id = eslint_client.id })
    else
        require("typescript").actions.organizeImports()
    end
end, {})
```

**Comment by jose-elias-alvarez** [comment]
Closing this as I believe it's out of scope.
