### ISSUE TITLE
`ENOENT: no such file or directory` when rename dir on `TypescriptRenameFile`

### ISSUE THREAD

**Issue by mbalazy** [jose-elias-alvarez/typescript.nvim#47]
When I want to move the file to the new dir (rename the path with non-existent folder)  I get `ENOENT: no such file or directory`. Is there any way to fix that?

For now I have to create the proper dir before running `:TypescriptRenameFile`

**Comment by jose-elias-alvarez** [comment]
We could theoretically handle this by changing the code so that it gets the parent directory of the new file and runs `mkdir` on it. PR welcome!

**Comment by gegoune** [comment]
Rather new option but should make it easier: https://github.com/neovim/neovim/pull/20835

**Comment by jacksonludwig** [comment]
Would this be as simple as adding a `:!mkdir -p <parent_of_filename>` before sending the rename `executeCommand`? Do we care if the server denies the rename and we are left with extra dirs?
