### ISSUE TITLE
Co-existing with another LSP (svelte)

### ISSUE THREAD

**Issue by ambiguous48** [jose-elias-alvarez/typescript.nvim#56]
I'm trying to configure this plugin/lsp with the svelte lsp, but there's one issue I can't seem to fix; making `organizeImports` work in `svelte` files.

If I add `svelte` to `filetypes`:

- OrganizeImports works (using either `:TypescriptOrganizeImports` or `require("typescript").actions.organizeImports()`)
- hover and go to definition act weird (I'm assuming that's because both the svelte lsp and typescript lsp are trying to perform the action, which doesn't sound right)

If I don't add `svelte` to `filetypes`:

- OrganizeImports doesn't work (nothing happens)
- hover and go to definition work OK

I think I know what to fix, but I'm not sure how to go about it. Specifically, I want to make this lsp only handle the `organizeImports` action, and nothing else (when the file is a svelte file). What's a good strategy to follow here, and where should it be implemented? If someone can point me to the section of the docs that can help me solve this that would also be appreciated. Thank you.

```lua
-- typescript.lua

local present, typescript = pcall(require, "typescript")

local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

if not present then
	return
end

typescript.setup({
	server = {
		on_attach = on_attach,
		capabilities = capabilities,
		filetypes = {
			"svelte", --  <----------- HERE
			"typescript",
			"typescriptreact",
			"typescript.tsx",
			"javascript", -- For jsdoc types
		},
	},
})
```

```lua
-- lspconfig.lua

local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require("lspconfig")

local servers = {
	"html",
	"cssls",
	"emmet_ls",
	"eslint",
	"rnix",
	"svelte",
	"tailwindcss",
	"grammarly",
	"jsonls",
}

for _, lsp in ipairs(servers) do
	lspconfig[lsp].setup({
		on_attach = on_attach,
		capabilities = capabilities,
	})
end
```

**Comment by jose-elias-alvarez** [comment]
It's a tricky situation that Neovim does not currently handle well. Theoretically, you can do this per project:

```lua
local is_in_svelte_project = function()
    -- use logic to determine if you're in a svelte project, e.g. using a specific file / marker
end

require("typescript").setup({
    server = {
        on_init = function(client)
            if is_in_svelte_project() then
                -- disable all capabilities you don't want to use
                -- this will mean that definition / hover requests will only go to the Svelte LSP
                client.server_capabilities.definitionProvider = false
                client.server_capabilities.hoverProvider = false
            end
        end,
    },
})
```

But I don't think there's a good way to do this per file. I think you'd have to write a wrapper around each affected function to only request from the specific language server you want to use, but that's pretty painful. For example, you could wrap [`vim.lsp.buf.hover()`](https://github.com/neovim/neovim/blob/a0b2c124a3cba591575ecf6d2dfe91f515c2ebe2/runtime/lua/vim/lsp/buf.lua#L40) to only request from `svelte` if it's attached.
