### ISSUE TITLE
Missing completion in JSX props

### ISSUE THREAD

**Issue by sQVe** [jose-elias-alvarez/typescript.nvim#61]
Hey 👋,

I noted, today, an issue with the completions provided for properties on JSX. It's it not being listed correctly and I'm unsure how to narrow down the issue.

See this issue for more context: https://github.com/typescript-language-server/typescript-language-server/issues/679

I would love any help I could get with this.

**Comment by jose-elias-alvarez** [comment]
Is this related to #34? Are you able to replicate it with a vanilla nvim-lspconfig setup? I can't tell from the linked issue, but if so, I'm not sure if there's anything we can do here.

**Comment by sQVe** [comment]
@jose-elias-alvarez Of course... 

I, for some reason, envisioned `typescript.nvim` as some kind of set-it-and-forget-it and didn't pass `capabilities`. The commit above solves all my issues.

As always, I'm very grateful for all your work and your quick responses Jose. You're a 💎.

Closing.
