### ISSUE TITLE
how to format diagnostic messages?

### ISSUE THREAD

**Issue by onelesd** [jose-elias-alvarez/typescript.nvim#63]
Is it possible to format the messages generated by tsserver? I'm trying to format the JSON types in the diagnostic message output with some line breaks for readability but can't figure where to hook into it.

**Comment by jose-elias-alvarez** [comment]
This isn't specific to the plugin, but you can override the default diagnostics handler:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = function(_, result, ctx, config)
    local client = lsp.get_client_by_id(ctx.client_id)
    if not (client and client.name == "tsserver") then
        return lsp.diagnostic.on_publish_diagnostics(nil, result, ctx, config)
    end

    for _, diagnostic in ipairs(result.diagnostics) do
        -- do whatever you want
    end

    return lsp.diagnostic.on_publish_diagnostics(nil, result, ctx, config)
end
```

**Comment by mmirus** [comment]
@onelesd If you're willing, please share what you manage! I'm interested in seeing what's possible. :pray:
