### ISSUE TITLE
ttag auto-import issue

### ISSUE THREAD

**Issue by skoch13** [jose-elias-alvarez/typescript.nvim#71]
Hi, 

First of all I'd like to thank you for your work. This plugin works almost perfectly 🙂

The issue I'm facing is the following:

STR:
* use `t` from [ttag](https://github.com/ttag-org/ttag)
* execute `Add missing imports` command via `null-ls`

Expected Results:
`import {t} from 'ttag';`

Actual Results: 
`import {t} from 'ttag\types';`

Is this an issue with the library and exports it provides?

**Comment by jose-elias-alvarez** [comment]
The results come straight from the language server, so there's nothing we can do about this. I believe I've seen similar issues on the [language server repository](https://github.com/typescript-language-server/typescript-language-server).
