### ISSUE TITLE
Question: How to run commands synchronously to each other

### ISSUE THREAD

**Issue by zer09** [jose-elias-alvarez/typescript.nvim#75]
I would like to run some of the actions command successively how should I do it? for now I have this

```lua
 vim.api.nvim_create_autocmd("BufWritePre", {
 	group = augroupTS,
 	buffer = bufnr,
 	callback = function()
 		ts.actions.addMissingImports({ sync = true })
 		ts.actions.removeUnused({ sync = true })
 		ts.actions.fixAll({ sync = true })
 		ts.actions.organizeImports({ sync = true })
 	end,
 })

```

This gives me inconsistent output, sometimes the `removeUnused` or `addMisingImports` is not executed, I need to resave the files several times should that I will get the expected output

**Comment by jose-elias-alvarez** [comment]
Not really possible, see #5.
