### ISSUE TITLE
Filtering error codes

### ISSUE THREAD

**Issue by LandonSchropp** [jose-elias-alvarez/typescript.nvim#76]
Occassionally, I have to work with a file that's a CommonJS module. Lately, the `File is a CommonJS module; it may be converted to an ES module.` diagnostic messages have been bugging me.

After a bit of digging, I ran across a [StackOverflow answer](https://stackoverflow.com/a/70294761/262125) that suggested that there was a `filter_out_diagnostics_by_code` option in nvim-lsp-ts-utils that could be used to filter out this diagnostic message (`80001`).

``` lua
require('lspconfig').tsserver.setup({
    on_attach = function(client, bufnr)
        require('nvim-lsp-ts-utils').setup({
            filter_out_diagnostics_by_code = { 80001 },
        })
        require('nvim-lsp-ts-utils').setup_client(client)
    end,
})
```

I looked, but there doesn't seem to be an equivalent configuration setting in typescript.nvim. Is there a preferred way to accomplish this? I found an approach in [this Reddit thread](https://www.reddit.com/r/neovim/comments/nv3qh8/comment/h1tx1rh/), but I was wondering if there was an easier way.

**Comment by jose-elias-alvarez** [comment]
I think the approach in the Reddit thread is what I'd recommend, too. The reason a similar option isn't included here is because this isn't really specific to `typescript-language-server` and can be handled pretty easily using a snippet.

**Comment by binhtran432k** [comment]
@LandonSchropp, @jose-elias-alvarez, I just found the alternative in `typescript-language-server`, hope it will help you.
```lua
require("typescript").setup({
  server = {
    -- ...
    settings={
      -- specify some or all of the following settings if you want to adjust the default behavior
      diagnostics = {
        ignoredCodes = { 80001 },
      },
    },
    -- ...
  },
})
```

**Comment by jose-elias-alvarez** [comment]
@binhtran432k Thanks for finding this! Since this actually can be configured on the language server's side I'm going to close this issue.

**Comment by LandonSchropp** [comment]
@binhtran432k That's perfect! Thank you for pointing it out. 🙂
