### ISSUE TITLE
[Feature request]  Implement Inlay Hints

### ISSUE THREAD

**Issue by jellydn** [jose-elias-alvarez/typescript.nvim#77]
# Feature Request: Implement Inlay Hints

## What

I propose the implementation of inlay hints for TypeScript in the typescript.nvim plugin. 

## Why

Inlay hints are a valuable addition to the LSP specification and have been implemented in the upstream Neovim project (see [Neovim/neovim#18086](https://github.com/neovim/neovim/issues/18086)). 

Inlay hints provide inline type information and other useful context directly in the code editor. This feature can significantly aid in understanding and navigating code, particularly in TypeScript where types are critical.

Several plugins have successfully implemented inlay hints for Neovim, such as:
- [lsp-inlayhints.nvim](https://github.com/lvimuser/lsp-inlayhints.nvim)
- [typescript-tools.nvim](https://github.com/pmizio/typescript-tools.nvim)
- [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim)

Bringing this feature to typescript.nvim would greatly enhance its functionality and provide more information directly within the editor.

## How

The exact implementation details are yet to be determined. However, there are a number of resources and reference implementations that could be used as a starting point.

**Comment by gegoune** [comment]
Typescript LSP provides that functionality already, you just need to enable it.
```lua
        typescript = {
          inlayHints = {
            includeInlayParameterNameHints = 'all',
            includeInlayParameterNameHintsWhenArgumentMatchesName = false,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayVariableTypeHints = true,
            includeInlayVariableTypeHintsWhenTypeMatchesName = false,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayEnumMemberValueHints = true,
          },
        },
        javascript = {
          inlayHints = {
            includeInlayParameterNameHints = 'all',
            includeInlayParameterNameHintsWhenArgumentMatchesName = false,
            includeInlayFunctionParameterTypeHints = true,
            includeInlayVariableTypeHints = true,
            includeInlayVariableTypeHintsWhenTypeMatchesName = false,
            includeInlayPropertyDeclarationTypeHints = true,
            includeInlayFunctionLikeReturnTypeHints = true,
            includeInlayEnumMemberValueHints = true,
          },
        },
```

**Comment by jellydn** [comment]
Thank you. I'm a little bit confused because what's mentioned in the readme is unclear.
<img width="938" alt="image" src="https://github.com/jose-elias-alvarez/typescript.nvim/assets/870029/0a18a91e-2ec6-48ff-b1f3-2f8b39762013">

**Comment by jacksonludwig** [comment]
> Thank you. I'm a little bit confused because what's mentioned in the readme is unclear.
> <img width="938" alt="image" src="https://github.com/jose-elias-alvarez/typescript.nvim/assets/870029/0a18a91e-2ec6-48ff-b1f3-2f8b39762013">
> 

Its because the Readme was not yet updated since this support was merged only a day or so ago :)

**Comment by ryoppippi** [comment]
```lua
require("typescript").setup({
   server = {
javascript = {
      inlayHints = {
        includeInlayEnumMemberValueHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
        includeInlayParameterNameHintsWhenArgumentMatchesName = true,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayVariableTypeHints = true,
      },
    },
    typescript = {
      inlayHints = {
        includeInlayEnumMemberValueHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
        includeInlayParameterNameHintsWhenArgumentMatchesName = true,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayVariableTypeHints = true,
      },
    },
})
```
Is this the correct way? I don't know why but it does not work

**Comment by ryoppippi** [comment]
OK I fixed !
it works

```
require("typescript").setup({
  server = {
    settings={
      javascript = {
        inlayHints = {
          includeInlayEnumMemberValueHints = true,
          includeInlayFunctionLikeReturnTypeHints = true,
          includeInlayFunctionParameterTypeHints = true,
          includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
          includeInlayParameterNameHintsWhenArgumentMatchesName = true,
          includeInlayPropertyDeclarationTypeHints = true,
          includeInlayVariableTypeHints = true,
        },
      },
      typescript = {
        inlayHints = {
          includeInlayEnumMemberValueHints = true,
          includeInlayFunctionLikeReturnTypeHints = true,
          includeInlayFunctionParameterTypeHints = true,
          includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
          includeInlayParameterNameHintsWhenArgumentMatchesName = true,
          includeInlayPropertyDeclarationTypeHints = true,
          includeInlayVariableTypeHints = true,
        },
      },
    },
  },
})

```

**Comment by jellydn** [comment]
@jacksonludwig 
> Its because the Readme was not yet updated since this support was merged only a day or so ago :)

Thanks for the clarification. It'd be fantastic if the Readme could be updated with usage details. I believe it would be beneficial for everyone.

**Comment by jacksonludwig** [comment]
> Thanks for the clarification. It'd be fantastic if the Readme could be updated with usage details. I believe it would be beneficial for everyone.

I'd make a PR to update the readme but I'm not sure if @jose-elias-alvarez would like to leave it up to the user to configure or have this plugin handle the options in some way.
